export const ASSET_TAG: string = 'v1.2.0-assets';
export const ASSET_BASE_URL: string =
  'http://192.168.1.109:8787';
export const ALLOW_INSECURE_HTTP_FOR_LOCAL_TESTS: boolean = true;
export const MANIFEST_SHA256: string =
  'fa6aa87ccb585136965bbc6fbb71a69ea8118ba1b3eed4067202ce71bc4ddbd7';

export const WEB_ORIGIN: string = 'https://cstf.invalid';
export const DOWNLOAD_BYTES: number = 2057808439;